using System.Collections.Generic;
using UnityEngine;

namespace WootingPlugin
{
    public enum HIDKeyboardScanCode
    {
        None = 0x00,
        ErrorRollover = 0x01,
        ErrorPostFail = 0x02,
        ErrorUndefined = 0x03,
        KeyA = 0x04,
        KeyB = 0x05,
        KeyC = 0x06,
        KeyD = 0x07,
        KeyE = 0x08,
        KeyF = 0x09,
        KeyG = 0x0a,
        KeyH = 0x0b,
        KeyI = 0x0c,
        KeyJ = 0x0d,
        KeyK = 0x0e,
        KeyL = 0x0f,
        KeyM = 0x10,
        KeyN = 0x11,
        KeyO = 0x12,
        KeyP = 0x13,
        KeyQ = 0x14,
        KeyR = 0x15,
        KeyS = 0x16,
        KeyT = 0x17,
        KeyU = 0x18,
        KeyV = 0x19,
        KeyW = 0x1a,
        KeyX = 0x1b,
        KeyY = 0x1c,
        KeyZ = 0x1d,
        Key1 = 0x1e,
        Key2 = 0x1f,
        Key3 = 0x20,
        Key4 = 0x21,
        Key5 = 0x22,
        Key6 = 0x23,
        Key7 = 0x24,
        Key8 = 0x25,
        Key9 = 0x26,
        Key0 = 0x27,
        KeyEnter = 0x28,
        KeyESC = 0x29,
        KeyBackspace = 0x2a,
        KeyTab = 0x2b,
        KeySpace = 0x2c,
        KeyMinus = 0x2d,
        KeyEqual = 0x2e,
        KeyLeftBrace = 0x2f,
        KeyRightBrace = 0x30,
        KeyBackSlash = 0x31,
        KeyHashTilde = 0x32,
        KeySemicolon = 0x33,
        KeyApostrophe = 0x34,
        KeyGrave = 0x35,
        KeyComma = 0x36,
        KeyPeriod = 0x37,
        KeyForwardSlash = 0x38,
        KeyCapslock = 0x39,
        KeyF1 = 0x3a,
        KeyF2 = 0x3b,
        KeyF3 = 0x3c,
        KeyF4 = 0x3d,
        KeyF5 = 0x3e,
        KeyF6 = 0x3f,
        KeyF7 = 0x40,
        KeyF8 = 0x41,
        KeyF9 = 0x42,
        KeyF10 = 0x43,
        KeyF11 = 0x44,
        KeyF12 = 0x45,
        KeyPrintScreen = 0x46,
        KeyScrollLock = 0x47,
        KeyPause = 0x48,
        KeyInsert = 0x49,
        KeyHome = 0x4a,
        KeyPageUp = 0x4b,
        KeyDelete = 0x4c,
        KeyEnd = 0x4d,
        KeyPageDown = 0x4e,
        KeyRight = 0x4f,
        KeyLeft = 0x50,
        KeyDown = 0x51,
        KeyUp = 0x52,
        KeyNPNumlock = 0x53,
        KeyNPSlash = 0x54,
        KeyNPAsterisk = 0x55,
        KeyNPMinus = 0x56,
        KeyNPPlus = 0x57,
        KeyNPEnter = 0x58,
        KeyNP1 = 0x59,
        KeyNP2 = 0x5a,
        KeyNP3 = 0x5b,
        KeyNP4 = 0x5c,
        KeyNP5 = 0x5d,
        KeyNP6 = 0x5e,
        KeyNP7 = 0x5f,
        KeyNP8 = 0x60,
        KeyNP9 = 0x61,
        KeyNP0 = 0x62,
        KeyNPDOT = 0x63,
        Key102ND = 0x64,
        KeyCompose = 0x65,
        KeyPower = 0x66,
        KeyNPEqual = 0x67,
        KeyF13 = 0x68,
        KeyF14 = 0x69,
        KeyF15 = 0x6a,
        KeyF16 = 0x6b,
        KeyF17 = 0x6c,
        KeyF18 = 0x6d,
        KeyF19 = 0x6e,
        KeyF20 = 0x6f,
        KeyF21 = 0x70,
        KeyF22 = 0x71,
        KeyF23 = 0x72,
        KeyF24 = 0x73,
        KeyOpen = 0x74,
        KeyHelp = 0x75,
        KeyMenu = 0x76,
        KeySelect = 0x77,
        KeyStop = 0x78,
        KeyAgain = 0x79,
        KeyUndo = 0x7a,
        KeyCut = 0x7b,
        KeyCopy = 0x7c,
        KeyPaste = 0x7d,
        KeyFind = 0x7e,
        KeyMute = 0x7f,
        KeyVolumeUp = 0x80,
        KeyVolumeDown = 0x81,
        KeyCapsLockLocking = 0x82,
        KeyNumLockLocking = 0x83,
        KeyScrollLockLocking = 0x84,
        KeyBRComma = 0x85,
        KeyBREqual = 0x86,
        KeyRo = 0x87,
        KeyKatakanaHiragana = 0x88,
        KeyYen = 0x89,
        KeyHenken = 0x8a,
        KeyMuhenkan = 0x8b,
        KeyJPComma = 0x8c,
        KeyHanguel = 0x90,
        KeyHanja = 0x91,
        KeyKatakana = 0x92,
        KeyHiragana = 0x93,
        KeyZenkakuHankaku = 0x94,
        KeyNPLeftParentheses = 0xb6,
        KeyNPRightParentheses = 0xb7,
        KeyLeftControl = 0xe0,
        KeyLeftShift = 0xe1,
        KeyLeftAlt = 0xe2,
        KeyLeftMeta = 0xe3,
        KeyRightControl = 0xe4,
        KeyRightShift = 0xe5,
        KeyRightAlt = 0xe6,
        KeyRightMeta = 0xe7,
        MediaPlayPause = 0xe8,
        MediaStopCD = 0xe9,
        MediaPrevious = 0xea,
        MediaNext = 0xeb,
        MediaEjectCD = 0xec,
        MediaVolumeUp = 0xed,
        MediaVolumeDown = 0xee,
        MediaMute = 0xef,
        MediaWWW = 0xf0,
        MediaBack = 0xf1,
        MediaForward = 0xf2,
        MediaStop = 0xf3,
        MediaFind = 0xf4,
        MediaScrollUp = 0xf5,
        MediaScrollDown = 0xf6,
        MediaEdit = 0xf7,
        MediaSleep = 0xf8,
        MediaCoffee = 0xf9,
        MediaRefresh = 0xfa,
        MediaCalculator = 0xfb,
    }
    public static class ScanCode
    {
        private static Dictionary<KeyCode, HIDKeyboardScanCode> keyCodeTranslation = new Dictionary<KeyCode, HIDKeyboardScanCode>
        {
            { KeyCode.A, HIDKeyboardScanCode.KeyA },
            { KeyCode.B, HIDKeyboardScanCode.KeyB },
            { KeyCode.C, HIDKeyboardScanCode.KeyC },
            { KeyCode.D, HIDKeyboardScanCode.KeyD },
            { KeyCode.E, HIDKeyboardScanCode.KeyE },
            { KeyCode.F, HIDKeyboardScanCode.KeyF },
            { KeyCode.G, HIDKeyboardScanCode.KeyG },
            { KeyCode.H, HIDKeyboardScanCode.KeyH },
            { KeyCode.I, HIDKeyboardScanCode.KeyI },
            { KeyCode.J, HIDKeyboardScanCode.KeyJ },
            { KeyCode.K, HIDKeyboardScanCode.KeyK },
            { KeyCode.L, HIDKeyboardScanCode.KeyL },
            { KeyCode.M, HIDKeyboardScanCode.KeyM },
            { KeyCode.N, HIDKeyboardScanCode.KeyN },
            { KeyCode.O, HIDKeyboardScanCode.KeyO },
            { KeyCode.P, HIDKeyboardScanCode.KeyP },
            { KeyCode.Q, HIDKeyboardScanCode.KeyQ },
            { KeyCode.R, HIDKeyboardScanCode.KeyR },
            { KeyCode.S, HIDKeyboardScanCode.KeyS },
            { KeyCode.T, HIDKeyboardScanCode.KeyT },
            { KeyCode.U, HIDKeyboardScanCode.KeyU },
            { KeyCode.V, HIDKeyboardScanCode.KeyV },
            { KeyCode.W, HIDKeyboardScanCode.KeyW },
            { KeyCode.X, HIDKeyboardScanCode.KeyX },
            { KeyCode.Y, HIDKeyboardScanCode.KeyY },
            { KeyCode.Z, HIDKeyboardScanCode.KeyZ },
            { KeyCode.Alpha1, HIDKeyboardScanCode.Key1 },
            { KeyCode.Alpha2, HIDKeyboardScanCode.Key2 },
            { KeyCode.Alpha3, HIDKeyboardScanCode.Key3 },
            { KeyCode.Alpha4, HIDKeyboardScanCode.Key4 },
            { KeyCode.Alpha5, HIDKeyboardScanCode.Key5 },
            { KeyCode.Alpha6, HIDKeyboardScanCode.Key6 },
            { KeyCode.Alpha7, HIDKeyboardScanCode.Key7 },
            { KeyCode.Alpha8, HIDKeyboardScanCode.Key8 },
            { KeyCode.Alpha9, HIDKeyboardScanCode.Key9 },
            { KeyCode.Alpha0, HIDKeyboardScanCode.Key0 },
            { KeyCode.Keypad1, HIDKeyboardScanCode.KeyNP1 },
            { KeyCode.Keypad2, HIDKeyboardScanCode.KeyNP2 },
            { KeyCode.Keypad3, HIDKeyboardScanCode.KeyNP3 },
            { KeyCode.Keypad4, HIDKeyboardScanCode.KeyNP4 },
            { KeyCode.Keypad5, HIDKeyboardScanCode.KeyNP5 },
            { KeyCode.Keypad6, HIDKeyboardScanCode.KeyNP6 },
            { KeyCode.Keypad7, HIDKeyboardScanCode.KeyNP7 },
            { KeyCode.Keypad8, HIDKeyboardScanCode.KeyNP8 },
            { KeyCode.Keypad9, HIDKeyboardScanCode.KeyNP9 },
            { KeyCode.Keypad0, HIDKeyboardScanCode.KeyNP0 },
            { KeyCode.KeypadEnter, HIDKeyboardScanCode.KeyNPEnter },
            { KeyCode.KeypadDivide, HIDKeyboardScanCode.KeyNPSlash },
            { KeyCode.KeypadMultiply, HIDKeyboardScanCode.KeyNPAsterisk },
            { KeyCode.KeypadMinus, HIDKeyboardScanCode.KeyNPMinus },
            { KeyCode.KeypadPlus, HIDKeyboardScanCode.KeyNPPlus },
            { KeyCode.KeypadPeriod, HIDKeyboardScanCode.KeyNPDOT },
            { KeyCode.UpArrow, HIDKeyboardScanCode.KeyUp },
            { KeyCode.DownArrow, HIDKeyboardScanCode.KeyDown },
            { KeyCode.LeftArrow, HIDKeyboardScanCode.KeyLeft },
            { KeyCode.RightArrow, HIDKeyboardScanCode.KeyRight },
            { KeyCode.Space, HIDKeyboardScanCode.KeySpace },
            { KeyCode.Tab, HIDKeyboardScanCode.KeyTab },
            { KeyCode.LeftShift, HIDKeyboardScanCode.KeyLeftShift },
            { KeyCode.LeftControl, HIDKeyboardScanCode.KeyLeftControl },
            { KeyCode.LeftAlt, HIDKeyboardScanCode.KeyLeftAlt },
            { KeyCode.RightShift, HIDKeyboardScanCode.KeyRightShift },
            { KeyCode.RightControl, HIDKeyboardScanCode.KeyRightControl },
            { KeyCode.RightAlt, HIDKeyboardScanCode.KeyRightAlt },
        };

        public static HIDKeyboardScanCode TranslateFromKeyCode(KeyCode code)
        {
            if (keyCodeTranslation.ContainsKey(code))
            {
                return keyCodeTranslation[code];
            }
            return HIDKeyboardScanCode.None;
        }
    }
}
